#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

async function main(args) {
  const outDir = path.resolve(args.outDir || args.out || 'generated-deck');
  fs.mkdirSync(outDir, { recursive: true });

  const deckPath = path.join(outDir, 'deck.json');
  const htmlPath = path.join(outDir, 'index.html');
  const pptxPath = path.join(outDir, 'deck.pptx');
  const qualityPath = path.join(outDir, 'quality.json');
  const readmePath = path.join(outDir, 'README.md');
  const manifestPath = path.join(outDir, 'manifest.json');
  const inputType = args.brief ? 'brief' : args.content ? 'content' : args.pptx ? 'pptx' : '';

  if (args.brief) {
    run('node', ['scripts/plan-deck.cjs', '--brief', args.brief, '--output', deckPath, ...(args.template ? ['--template', args.template] : [])]);
  } else if (args.content) {
    const content = path.resolve(args.content);
    if (content.endsWith('.json')) {
      fs.copyFileSync(content, deckPath);
    } else {
      run('node', ['scripts/generate.cjs', '--template', args.template || 'academic-tech-dark', '--content', content, '--output', htmlPath, '--exportDeck', deckPath]);
    }
  } else if (args.pptx) {
    run('node', ['scripts/import-pptx.cjs', '--input', path.resolve(args.pptx), '--output', deckPath, ...(args.template ? ['--template', args.template] : [])]);
  } else {
    console.error('Please provide --brief, --content, or --pptx');
    process.exit(1);
  }

  run('node', ['scripts/quality-deck.cjs', '--content', deckPath]);
  const quality = captureJson('node', ['scripts/quality-deck.cjs', '--content', deckPath, '--json']);
  fs.writeFileSync(qualityPath, `${JSON.stringify(quality, null, 2)}\n`, 'utf8');
  run('node', ['scripts/generate.cjs', '--content', deckPath, '--output', htmlPath]);
  const shouldExportPptx = args.pptxOut !== false && args.noPptx !== true;
  if (shouldExportPptx) {
    run('node', ['scripts/export-pptx.cjs', '--content', deckPath, '--output', pptxPath]);
  }

  const deck = JSON.parse(fs.readFileSync(deckPath, 'utf8'));
  const manifest = {
    generatedAt: new Date().toISOString(),
    inputType,
    title: deck.title || deck.slides?.[0]?.title || '',
    template: deck.template,
    category: deck.meta?.category || '',
    slides: deck.slides?.length || 0,
    quality: { score: quality.score, level: quality.level },
    outputs: {
      deckJson: path.relative(outDir, deckPath),
      html: path.relative(outDir, htmlPath),
      pptx: shouldExportPptx ? path.relative(outDir, pptxPath) : null,
      quality: path.relative(outDir, qualityPath),
    },
  };
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  fs.writeFileSync(readmePath, packageReadme(manifest), 'utf8');

  console.log('\nCreated deck package:');
  console.log(`  Deck JSON: ${deckPath}`);
  console.log(`  HTML: ${htmlPath}`);
  if (shouldExportPptx) console.log(`  PPTX: ${pptxPath}`);
  console.log(`  Quality: ${qualityPath}`);
  console.log(`  Manifest: ${manifestPath}`);
}

function run(command, args) {
  const result = spawnSync(command, args, { cwd: path.resolve(__dirname, '..'), stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status || 1);
}

function captureJson(command, args) {
  const result = spawnSync(command, args, { cwd: path.resolve(__dirname, '..'), encoding: 'utf8' });
  if (result.status !== 0) {
    process.stderr.write(result.stderr || result.stdout || '');
    process.exit(result.status || 1);
  }
  return JSON.parse(result.stdout);
}

function packageReadme(manifest) {
  const outputs = [
    `- HTML: \`${manifest.outputs.html}\``,
    `- Deck JSON: \`${manifest.outputs.deckJson}\``,
    manifest.outputs.pptx ? `- PPTX: \`${manifest.outputs.pptx}\`` : '',
    `- Quality report: \`${manifest.outputs.quality}\``,
  ].filter(Boolean).join('\n');

  return `# ${manifest.title || 'Generated HIT PPT Deck'}

This folder was generated by the HIT Shenzhen HTML PPT template system.

## Summary

- Template: \`${manifest.template}\`
- Category: \`${manifest.category || 'n/a'}\`
- Slides: ${manifest.slides}
- Quality: ${manifest.quality.score}/100 (${manifest.quality.level})
- Generated: ${manifest.generatedAt}

## Outputs

${outputs}

## How To Present

Open \`${manifest.outputs.html}\` in a browser. Use ArrowLeft/ArrowRight, PageUp/PageDown, Home/End, or click the left/right side of the slide.

## How To Edit

- Edit \`${manifest.outputs.deckJson}\` and regenerate HTML/PPTX from the repository root.
- Use the PPTX file when native PowerPoint editing is required.
`;
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].replace('--', '');
      const val = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
      args[key] = val;
    }
  }
  return args;
}

main(parseArgs(process.argv.slice(2))).catch((error) => {
  console.error(error);
  process.exit(1);
});
