#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const outDir = path.join(root, 'public/assets/generated/icons');
fs.mkdirSync(outDir, { recursive: true });

const icons = [
  'agenda', 'analysis', 'archive', 'award', 'book', 'calendar', 'campus', 'chart',
  'check', 'clock', 'collaboration', 'compare', 'data', 'experiment', 'feedback',
  'flow', 'goal', 'group', 'idea', 'image', 'lab', 'leadership', 'logic', 'map',
  'method', 'metric', 'network', 'plan', 'presentation', 'process', 'profile',
  'quote', 'research', 'result', 'rocket', 'shield', 'spark', 'swot', 'team', 'timeline',
];

function symbol(name, i) {
  const hue = i % 3 === 0 ? '#005375' : i % 3 === 1 ? '#45d6c8' : '#d7b66f';
  const cx = 32;
  const cy = 32;
  const r = 20 + (i % 4);
  const spokes = Array.from({ length: 6 }, (_, index) => {
    const angle = (Math.PI * 2 * index) / 6;
    const x = cx + Math.cos(angle) * (r - 4);
    const y = cy + Math.sin(angle) * (r - 4);
    return `<circle cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="2.6"/>`;
  }).join('');

  if (/chart|data|metric|result/.test(name)) {
    return `<path d="M16 48V34M28 48V24M40 48V30M52 48V18"/><path d="M12 50H56"/>`;
  }
  if (/flow|process|timeline|plan/.test(name)) {
    return `<path d="M12 32H52"/><circle cx="16" cy="32" r="5"/><circle cx="32" cy="32" r="5"/><circle cx="48" cy="32" r="5"/><path d="M50 26l6 6-6 6"/>`;
  }
  if (/team|group|profile|leadership|collaboration/.test(name)) {
    return `<circle cx="24" cy="24" r="7"/><circle cx="43" cy="25" r="6"/><path d="M12 52c2-10 21-10 24 0"/><path d="M34 52c2-8 16-8 18 0"/>`;
  }
  if (/campus|book|research|lab|experiment/.test(name)) {
    return `<path d="M14 50V24l18-10 18 10v26"/><path d="M10 50h44"/><path d="M25 50V34h14v16"/><path d="M22 27h20"/>`;
  }
  if (/logic|network|swot|compare|analysis/.test(name)) {
    return `<circle cx="32" cy="32" r="${r}"/>${spokes}<path d="M32 12v40M12 32h40"/>`;
  }
  if (/award|goal|check|shield/.test(name)) {
    return `<path d="M32 10l18 8v13c0 12-8 19-18 23-10-4-18-11-18-23V18z"/><path d="M23 32l6 6 13-14"/>`;
  }
  return `<circle cx="32" cy="32" r="${r}"/><path d="M22 34l7 7 15-18"/><path d="M18 52l28-40"/>`;
}

for (const [index, name] of icons.entries()) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64" fill="none" stroke="#005375" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" role="img" aria-label="${name}">
<rect x="4" y="4" width="56" height="56" rx="12" fill="#f8fbff" stroke="#d7b66f" opacity=".98"/>
<g stroke="${index % 4 === 0 ? '#005375' : index % 4 === 1 ? '#45d6c8' : index % 4 === 2 ? '#A72126' : '#d7b66f'}">${symbol(name, index)}</g>
</svg>`;
  fs.writeFileSync(path.join(outDir, `${name}.svg`), svg);
}

fs.writeFileSync(path.join(outDir, 'README.md'), `# Generated Icon Set\n\n40 SVG icons for HIT HTML PPT templates. Generated by \`scripts/generate-icons.cjs\`.\n`);
console.log(`Generated ${icons.length} icons in ${path.relative(root, outDir)}`);
